# Generated by Django 2.2.16 on 2023-04-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_auto_20230228_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={
                'ordering': ('-title',),
                'verbose_name': 'группа статей ',
                'verbose_name_plural': 'группы статей',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={
                'default_related_name': 'posts',
                'ordering': ('-pub_date',),
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True, upload_to='posts/', verbose_name='Картинка'
            ),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(
                max_length=30, unique=True, verbose_name='читаемая часть URL'
            ),
        ),
    ]
